#!/bin/bash

./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/perlbench_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/perlbench_base.amd64-m64-gcc42-nn --workload_args "-I /home/minchan/spec2006" "-I /home/minchan/spec2006/lib"  "/home/minchan/spec2006/attrs.pl" &        
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/bzip_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/bzip2_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/input.program" "5" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/gcc_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/gcc_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/cccp.i" "-o" "/home/min chan/spec2006/cccp.s" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/bwaves_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/bwaves_base.amd64-m64-gcc42-nn &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/gromacs_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/gromacs_base.amd64-m64-gcc42-nn --workload_args "-silent" "-deffnm" "gromacs" "-nice" "0" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/mcf_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/mcf_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/inp.in" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/milc_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/milc_base.amd64-m64-gcc42-nn --workload_args "<" "/home/minchan/spec2006/su3imp.in" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/zeusmp_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/zeusmp_base.amd64-m64-gcc42-nn &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/gromacs_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/gromacs_base.amd64-m64-gcc42-nn --workload_args "-silent" "-deffnm" "gromacs" "-nice" "0" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/cactusADM_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/cactusADM_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/benchADM.par" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/leslie3d_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/leslie3d_base.amd64-m64-gcc42-nn --workload_args "<" "/home/minchan/spec2006/leslie3d.in" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/namd_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/namd_base.amd64-m64-gcc42-nn --workload_args "--input" "/home/minchan/spec2006/namd.input" "--iterations" "1" "--output" "/home/minchan/spec2006/namd.out" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/gobmk_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/gobmk_base.amd64-m64-gcc42-nn --workload_args "--quiet" "--mode" "gtp" "<" "/home/minchan/spec2006/capture.tst" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/soplex_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/soplex_base.amd64-m64-gcc42-nn --workload_args "-m10000" "/home/minchan/spec2006/test.mps" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/povray_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/povray_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/SPEC-benchmark-test.ini" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/calculix_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/calculix_base.amd64-m64-gcc42-nn --workload_args "-i" "/home/minchan/spec2006/beampic" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/hmmer_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/hmmer_base.amd64-m64-gcc42-nn --workload_args "--fixed" "0" "--mean" "325" "--num" "45000" "--sd" "200" "--seed" "0" "/home/minchan/spec2006/bombesin.hmm" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/sjeng_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/sjeng_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/test.txt" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/GemsFDTD_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/GemsFDTD_base.amd64-m64-gcc42-nn    &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/libquantum_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/libquantum_base.amd64-m64-gcc42-nn --workload_args "33" "5" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/h264ref_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/h264ref_base.amd64-m64-gcc42-nn --workload_args "-d" "/home/minchan/spec2006/foreman_test_encoder_baseline.cfg" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/tonto_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/tonto_base.amd64-m64-gcc42-nn &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/lbm_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/lbm_base.amd64-m64-gcc42-nn --workload_args "20" "/home/minchan/spec2006/reference.dat" "0" "1" "100_100_130_cf_a.of" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/omnetpp_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/omnetpp_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/omnetpp.ini" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/astar_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/astar_base.amd64-m64-gcc42-nn --workload_args "/home/minchan/spec2006/lake.cfg" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/wrf_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/wrf_base.amd64-m64-gcc42-nn &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/sphinx_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/sphinx_livepretend_base.amd64-m64-gcc42-nn --workload_args "ctlfile" "." "args.an4" &
./build/X86/gem5.opt --outdir=/home/minchan/projects/UFC/EXP1/specrand_base ufc_configs/EXP1.py --isa=X86 --workload=/home/minchan/spec2006/specrand_base.amd64-m64-gcc42-nn --workload_args "324342" "24239" &
